# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eauc <- function(theta, X, Y) {
    .Call(`_maxAUC_eauc`, theta, X, Y)
}

dqncpp <- function(theta, X, Y, var) {
    .Call(`_maxAUC_dqncpp`, theta, X, Y, var)
}

an_anchor <- function(theta, X, Y, var) {
    .Call(`_maxAUC_an_anchor`, theta, X, Y, var)
}

vn_anchor <- function(theta, X, Y, var) {
    .Call(`_maxAUC_vn_anchor`, theta, X, Y, var)
}

dn_anchor <- function(theta, X, Y, var) {
    .Call(`_maxAUC_dn_anchor`, theta, X, Y, var)
}

newton_raphson_anchor <- function(theta_initial, tol, iteration, gamma, X, Y, var) {
    .Call(`_maxAUC_newton_raphson_anchor`, theta_initial, tol, iteration, gamma, X, Y, var)
}

eauc_sort <- function(beta, X, Y, silence) {
    .Call(`_maxAUC_eauc_sort`, beta, X, Y, silence)
}

tauc_sort <- function(beta, X, Y, sigma0, silence) {
    .Call(`_maxAUC_tauc_sort`, beta, X, Y, sigma0, silence)
}

dtauc_opt <- function(beta, beta_k, X, Y, sigma0) {
    .Call(`_maxAUC_dtauc_opt`, beta, beta_k, X, Y, sigma0)
}

varauc <- function(beta, X, Y) {
    .Call(`_maxAUC_varauc`, beta, X, Y)
}

ddnormcpp <- function(x) {
    .Call(`_maxAUC_ddnormcpp`, x)
}

hessianpw <- function(beta, X, Y, var, w) {
    .Call(`_maxAUC_hessianpw`, beta, X, Y, var, w)
}

meatpw <- function(beta, X, Y, var) {
    .Call(`_maxAUC_meatpw`, beta, X, Y, var)
}

varbeta <- function(beta, X, Y, var, w) {
    .Call(`_maxAUC_varbeta`, beta, X, Y, var, w)
}

