# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eauc <- function(theta, X, Y) {
    .Call(`_maxAUC_eauc`, theta, X, Y)
}

dqncpp <- function(theta, X, Y, var) {
    .Call(`_maxAUC_dqncpp`, theta, X, Y, var)
}

an_anchor <- function(theta, X, Y, var) {
    .Call(`_maxAUC_an_anchor`, theta, X, Y, var)
}

vn_anchor <- function(theta, X, Y, var) {
    .Call(`_maxAUC_vn_anchor`, theta, X, Y, var)
}

dn_anchor <- function(theta, X, Y, var) {
    .Call(`_maxAUC_dn_anchor`, theta, X, Y, var)
}

newton_raphson_anchor <- function(theta_initial, tol, iteration, gamma, X, Y, var) {
    .Call(`_maxAUC_newton_raphson_anchor`, theta_initial, tol, iteration, gamma, X, Y, var)
}

eauc_l1 <- function(beta, X, Y, silence) {
    .Call(`_maxAUC_eauc_l1`, beta, X, Y, silence)
}

eauc_sort <- function(beta, X, Y, silence) {
    .Call(`_maxAUC_eauc_sort`, beta, X, Y, silence)
}

triang <- function(x, sigma0) {
    .Call(`_maxAUC_triang`, x, sigma0)
}

tauc_sort <- function(beta, X, Y, sigma0, silence) {
    .Call(`_maxAUC_tauc_sort`, beta, X, Y, sigma0, silence)
}

varauc_l1 <- function(beta, X, Y) {
    .Call(`_maxAUC_varauc_l1`, beta, X, Y)
}

dtauc_opt <- function(beta, beta_k, X, Y, sigma0, w, t) {
    .Call(`_maxAUC_dtauc_opt`, beta, beta_k, X, Y, sigma0, w, t)
}

vn <- function(beta, X, Y, var, anchor) {
    .Call(`_maxAUC_vn`, beta, X, Y, var, anchor)
}

an <- function(beta, X, Y, var, anchor) {
    .Call(`_maxAUC_an`, beta, X, Y, var, anchor)
}

dn <- function(beta, X, Y, var, anchor) {
    .Call(`_maxAUC_dn`, beta, X, Y, var, anchor)
}

